services:
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - /opt/paperless-ngx/data:/usr/src/paperless/data
      - /opt/paperless-ngx/media:/usr/src/paperless/media
      - /opt/paperless-ngx/export:/usr/src/paperless/export
      - /opt/paperless-ngx/consume:/usr/src/paperless/consume
  redis:
    image: redis:7
    container_name: paperless-redis
    restart: unless-stopped
  db:
    image: postgres:15
    container_name: paperless-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    volumes:
      - /opt/paperless-ngx/db:/var/lib/postgresql/data
